#!/bin/sh -e

usage() {
    echo "ubuild <configuration> <package tree> <mode> <output-dir>"
    echo
    echo "<mode> = host | target:$arch | toolchain:$arch"
    echo
    echo "Configuration is like openinkpot-i386-asimov or iplinux-amd64-zelazny"
}

if [ $# -ne 4 ]; then
    usage
    exit 1
fi

CONFIGURATION="$1"
TREE="$2"
MODE="$3"
OUTPUT_DIR="$4"

[ -f ubuild.conf ] && . ./ubuild.conf && PATH=$(pwd):$PATH || . /etc/ubuild/ubuild.conf

. ubuild-functions

case "$MODE" in
    host)
        pbuildit "$TREE" "$OUTPUT_DIR"
        ;;
    target:*)
        TARGET_ARCH=${MODE#target:}
        pbuildit "$TREE" "$OUTPUT_DIR" "$TARGET_ARCH"
        ;;
    toolchain:*)
        ARCH=${MODE#toolchain:}
        echo "ERR: Building toolchains is not implemented yet"
        exit 1
        ;;
    *)
        usage
        exit 1
        ;;
esac
